Console.BackgroundColor = ConsoleColor.DarkRed;
Console.ForegroundColor = ConsoleColor.Black;
Console.Write("S");
Console.BackgroundColor = ConsoleColor.Black;
Console.ForegroundColor = ConsoleColor.White;
Console.Write("Ã");
Console.ForegroundColor = ConsoleColor.Red;
Console.Write("O");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.ForegroundColor = ConsoleColor.White;
Console.Write("\tP");
Console.BackgroundColor = ConsoleColor.Black;
Console.ForegroundColor = ConsoleColor.Red;
Console.Write("A");
Console.ForegroundColor = ConsoleColor.White;
Console.Write("U");
Console.ForegroundColor = ConsoleColor.Red;
Console.Write("L");
Console.ForegroundColor = ConsoleColor.White;
Console.Write("O");